- name: Add pmm2 user to mysql instance
  mysql_user:
    login_user: "{{ pmm2_client_services.mysql.login_user }}"
    login_password: "{{ pmm2_client_services.mysql.login_password }}"
    login_host: "{{ pmm2_client_services.mysql.login_host }}"
    login_port: "{{ pmm2_client_services.mysql.login_port }}"
    user: "{{ pmm2_client_services.mysql.user }}"
    password: "{{ pmm2_client_services.mysql.password }}"
    plugin: "{{ pmm2_client_services.mysql.plugin }}"
    priv: "{{ pmm2_client_services.mysql.privileges }}"
    host: "%"
    state: present
  when: pmm2_client_services.mysql.create_user

- name: Execute runtime mysql queries
  mysql_query:
    login_user: "{{ pmm2_client_services.mysql.login_user }}"
    login_password: "{{ pmm2_client_services.mysql.login_password }}"
    login_host: "{{ pmm2_client_services.mysql.login_host }}"
    login_port: "{{ pmm2_client_services.mysql.login_port }}"
    login_db: performance_schema
    query:
      - UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME LIKE '%statements%';
      - SET GLOBAL innodb_monitor_enable = all;

- name: Determine mysql version
  mysql_query:
    login_user: "{{ pmm2_client_services.mysql.login_user }}"
    login_password: "{{ pmm2_client_services.mysql.login_password }}"
    login_host: "{{ pmm2_client_services.mysql.login_host }}"
    login_port: "{{ pmm2_client_services.mysql.login_port }}"
    query: SHOW VARIABLES LIKE "version";
  register: mysql_version

- name: Determine mysql version comment
  mysql_query:
    login_user: "{{ pmm2_client_services.mysql.login_user }}"
    login_password: "{{ pmm2_client_services.mysql.login_password }}"
    login_host: "{{ pmm2_client_services.mysql.login_host }}"
    login_port: "{{ pmm2_client_services.mysql.login_port }}"
    query: SHOW VARIABLES LIKE "version_comment";
  register: mysql_version_comment

- name: Execute MariaDB 10.5.7 or lower runtime queries
  mysql_query:
    login_user: "{{ pmm2_client_services.mysql.login_user }}"
    login_password: "{{ pmm2_client_services.mysql.login_password }}"
    login_host: "{{ pmm2_client_services.mysql.login_host }}"
    login_port: "{{ pmm2_client_services.mysql.login_port }}"
    login_db: performance_schema
    query:
      - UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES' WHERE NAME LIKE 'statement/%';
      - UPDATE performance_schema.setup_consumers SET ENABLED = 'YES' WHERE NAME LIKE '%statements%';
  when: > 
    mysql_version_comment.query_result.0.0.Value is regex('mariadb', ignorecase=true) and 
    mysql_version.query_result.0.0.Value is version('10.5.7', '<=')

- name: Register mysql service to pmm2 server
  command: >-
    pmm-admin add mysql
    --username={{ pmm2_client_services.mysql.user | quote }}
    --password={{ pmm2_client_services.mysql.password | quote }}
    {{ "--tls --tls-skip-verify" if pmm2_client_services.mysql.tls else omit }}
    --query-source={{ pmm2_client_services.mysql.query_source | quote }}
    --host={{ pmm2_client_services.mysql.login_host | quote }}
    --port={{ pmm2_client_services.mysql.login_port | quote }}
    --service-name={{ pmm2_client_services.mysql.name | quote }}
  when: pmm2_client_services.mysql.name not in pmm_admin_list.stdout 

